name: shopping_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.5
  country_picker: ^2.0.21
  coupon_uikit: ^0.2.0
  dio: ^5.3.2
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_slideshow: ^0.1.6
  flutter_otp_text_field: ^1.1.1
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_widget_from_html_core: ^0.10.3
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.4.2
  woocommerce_api: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1  
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - .env
