// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["apiKey"] ?? "No API key specified",
    appId: dotenv.env["appId"] ?? "No App ID specified",
    messagingSenderId: '237481333227',
    projectId: 'shoppingapp-f569d',
    authDomain: 'shoppingapp-f569d.firebaseapp.com',
    storageBucket: 'shoppingapp-f569d.appspot.com',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["apiKey"] ?? "No API key specified",
    appId: dotenv.env["appId"] ?? "No App ID specified",
    messagingSenderId: '237481333227',
    projectId: 'shoppingapp-f569d',
    storageBucket: 'shoppingapp-f569d.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["apiKey"] ?? "No API key specified",
    appId: dotenv.env["appId"] ?? "No App ID specified",
    messagingSenderId: '237481333227',
    projectId: 'shoppingapp-f569d',
    storageBucket: 'shoppingapp-f569d.appspot.com',
    iosClientId:
        '237481333227-pl27iic1h0j2qlp1suvddhginingruff.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env["apiKey"] ?? "No API key specified",
    appId: dotenv.env["appId"] ?? "No App ID specified",
    messagingSenderId: '237481333227',
    projectId: 'shoppingapp-f569d',
    storageBucket: 'shoppingapp-f569d.appspot.com',
    iosClientId:
        '237481333227-pcegg2f53rt7cktnp52e9du3s0j5hb2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
